---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth-test
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-test
  annotations:
    kubernetes.io/service-account.name: vault-auth-test
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-test-tokenreview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth-test
    namespace: staging
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret
spec:
  vaultAuthRef: vault-auth
  mount: applications
  type: kv-v2
  path: gateway
  refreshAfter: 10s
  destination:
    create: true
    name: vso-gateway
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
spec:
  method: kubernetes
  mount: vso
  kubernetes:
    role: vso
    serviceAccount: vault-auth-test
    audiences:
    - vault